### PR TITLE
Mobile friendly

### PR DESCRIPTION
**Pull request by Mordil**
Added responsive / adaptive design for the site.

This includes a refactor of the app (I'm sorry! I didn't mean to 😞).

Developed using: http://responsivedesignchecker.com/checker.php?url=localhost%3A8080&width=1400&height=700

Tested on:

MacOS
Safari
Windows
Chrome
Edge
Internet Explorer
Firefox

### CODE REVIEW

**Review by tanner0101 — DISMISSED** [review]
Really awesome job on this! Thank you. Only comment I would say is to reduce the padding on top/below the terminal screenshot a tiny bit.

screen shot 2018-05-07 at 3 26 20 pm

(also might be nice if the stoplight were a bit smaller)

After that, this is good to merge :D

**Comment by Mordil** [comment]
How does this look? I removed the default margin for `pre` tags up to the `tablet` size class.

new-sizing

**Comment by tanner0101** [comment]
LGTM. :shipit:

**Review by tanner0101 — APPROVED** [review]

**Comment by penny-coin** [comment]
Hey @Mordil, you just merged a pull request, have a coin! 

You now have 1 coins.

**Pull request merged**
