### PR TITLE
Russian localization added

### PR DESCRIPTION
**Pull request by makoni**

### CODE REVIEW

**Review by tanner0101 — COMMENTED** [review]
Code changes look great, thanks! We just need a third party to approve and we can merge. I'll post in Vapor chat's Russian channel to see if anyone can assist.

**Comment by nerzh** [comment]
Changes look good. I confirm this. Please approve.

**Review by tanner0101 — APPROVED** [review]
Thanks @makoni and @woodcrust!

**Comment by penny-coin** [comment]
Hey @makoni, you just merged a pull request, have a coin! 

You now have 1 coins.

**Comment by tanner0101** [comment]
screen shot 2019-03-01 at 8 50 41 pm

**Pull request merged**
