### PR TITLE
add spanish (español) localization

### PR DESCRIPTION
**Pull request by tanner0101**
Adds Spanish localization to vapor.codes website.

### CODE REVIEW

**Review by Mordil — DISMISSED** [review]
Who provided this translation, and do we have a 3rd party person who feels up to the task of verifying it?

**Review by AxelCB — CHANGES_REQUESTED** [review]
Instead of writing a detail of each thing that should be changed, I [attach a modified version of the file](https://github.com/vapor/website/files/2897291/es.txt) since I changed most of the lines, with txt extension since GitHub doesn't allow JS files. 

The contribute section in english gives me the feeling you're inviting new users to collaborate (tell me if I'm wrong) so I rephrased what was written to give this idea to readers.

Lines modified:
3,7,15,16,17,20,23,26,27,30,31,40

Any feedback is welcome, and I don't mind explaining any of the changes I made but they were a lot to explain here each one.

**Comment by tanner0101** [comment]
@AxelCB thanks! I took the liberty of converting that into a PR here: https://github.com/vapor/website/pull/32.

**Comment by tanner0101** [comment]
I just had the original author review those changes, and he says they look good. So we have two parties approving this one now, I'll go ahead and merge. Thanks again @AxelCB

**Comment by penny-coin** [comment]
Hey @tanner0101, you just merged a pull request, have a coin! 

You now have 1090 coins.

**Comment by AxelCB** [comment]
Glad to be able to help @tanner0101 !

**Comment by tanner0101** [comment]
screen shot 2019-02-23 at 5 38 34 pm

**Pull request merged**
